'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function SiteFooter() {
  const pathname = usePathname();

  // Hide footer on admin pages
  if (pathname.startsWith('/admin')) return null;

  return (
    <footer className="site-footer">
      <div className="ft-inner">
        <div className="ft-brand">
          <Link href="/" className="ft-logo">
            <span className="nav-mark">B</span>
            <strong>Baseflow Institute</strong>
          </Link>
          <p>Sustained research for global resilience.<br />AI-generated. Evidence-based. Open access.</p>
        </div>
        <div className="ft-col">
          <h4>Research</h4>
          <Link href="/library">Library</Link>
          <a href="/feed.xml">RSS Feed</a>
          <a href="/api/articles" target="_blank" rel="noreferrer">API</a>
        </div>
        <div className="ft-col">
          <h4>Organisation</h4>
          <Link href="/about">About</Link>
          <Link href="/about">Methodology</Link>
        </div>
        <div className="ft-col">
          <h4>Connect</h4>
          <a href="mailto:contact@baseflow.institute">Contact</a>
        </div>
      </div>
      <div className="ft-bottom">
        <p>&copy; {new Date().getFullYear()} Baseflow Institute. Research generated by AI with real-world data. Always verify critical decisions with primary sources.</p>
      </div>
    </footer>
  );
}
