'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';

type ArticlePreview = {
  slug: string;
  title: string;
  summary: string;
  tags: string[];
  template: string;
  region?: string;
  publishedAt: string;
  wordCount: number;
};

type TagCount = {
  tag: string;
  count: number;
};

const startCards = [
  {
    href: '/library',
    title: 'Explore the research library',
    description: 'Jump straight into reports by theme, geography, or keyword without digging through menus.',
    cta: 'Browse reports',
    image: '/illustrations/open-library.svg',
    alt: 'Illustration of an open research library dashboard.',
  },
  {
    href: '/about',
    title: 'Understand the methodology',
    description: 'See how data collection, planning, drafting, and fact-checking fit together before you read.',
    cta: 'See the process',
    image: '/illustrations/briefing-signal.svg',
    alt: 'Illustration of a research workflow dashboard with charts and notes.',
  },
  {
    href: '#newsletter',
    title: 'Stay updated with new briefs',
    description: 'Subscribe once and get notified when fresh climate and development research is published.',
    cta: 'Join the newsletter',
    image: '/illustrations/research-network.svg',
    alt: 'Illustration of a connected research network with global signals.',
  },
];

export default function HomePage() {
  const [articles, setArticles] = useState<ArticlePreview[]>([]);
  const [tags, setTags] = useState<TagCount[]>([]);
  const [totalPublished, setTotalPublished] = useState(0);
  const [email, setEmail] = useState('');
  const [subscribeStatus, setSubscribeStatus] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      fetch('/api/articles?limit=6').then(r => r.ok ? r.json() : { articles: [], total: 0 }),
      fetch('/api/articles/tags').then(r => r.ok ? r.json() : { tags: [] }),
    ]).then(([articlesData, tagsData]) => {
      setArticles(articlesData.articles || []);
      setTags(tagsData.tags || []);
      setTotalPublished(articlesData.total || 0);
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  const handleSubscribe = async () => {
    if (!email.trim() || !email.includes('@')) {
      setSubscribeStatus('Please enter a valid email.');
      return;
    }
    try {
      const res = await fetch('/api/subscribe', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email }),
      });
      if (res.ok) {
        setSubscribeStatus('Subscribed! You\'ll receive updates on new research.');
        setEmail('');
      } else {
        const data = await res.json();
        setSubscribeStatus(data.error || 'Subscription failed.');
      }
    } catch {
      setSubscribeStatus('Connection error. Try again.');
    }
  };

  const formatDate = (iso: string) =>
    new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const tagLabels: Record<string, string> = {
    climate: 'Climate', water: 'Water Security', energy: 'Clean Energy',
    agriculture: 'Agriculture', health: 'Health', policy: 'Policy',
    finance: 'Finance', resilience: 'Resilience', biodiversity: 'Biodiversity',
    urbanization: 'Urbanization', education: 'Education', gender: 'Gender Equity',
    'sub-saharan-africa': 'Sub-Saharan Africa', 'south-asia': 'South Asia',
    'southeast-asia': 'Southeast Asia', 'latin-america': 'Latin America',
    'pacific-islands': 'Pacific Islands', 'middle-east': 'MENA',
  };

  return (
    <main className="pub" id="main-content">
      {/* ─── Hero ─── */}
        <section className="hero">
          <div className="hero-layout">
            <div className="hero-inner">
              <p className="hero-eyebrow">Open-access research powered by AI</p>
              <h1>Sustained Research for Global Resilience</h1>
              <p className="hero-sub">
                Evidence-based policy briefs on climate adaptation, water security,
                clean energy, and sustainable development&mdash;generated by AI agents,
                grounded in real-world data, free for everyone.
              </p>
              <div className="hero-actions">
                <Link href="/library" className="btn-primary">
                  Browse Research Library
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M3.5 8h9M8.5 4l4 4-4 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
                </Link>
                <a href="#pipeline" className="btn-ghost">See How It Works</a>
              </div>
              <div className="hero-signals" aria-label="Platform highlights">
                <span className="hero-signal">Public data sources</span>
                <span className="hero-signal">Fact-checking pass</span>
                <span className="hero-signal">Free API and RSS</span>
              </div>
            </div>

            <div className="hero-visual">
              <div className="hero-visual-card">
                <div className="hero-image-shell">
                  <Image
                    src="/illustrations/research-network.svg"
                    alt="Illustration of a policy research dashboard connected to global data sources."
                    width={640}
                    height={480}
                    priority
                  />
                </div>
                <div className="hero-visual-summary">
                  <div className="hero-summary-item">
                    <strong>Weekly-ready briefing flow</strong>
                    <span>Research, draft, verify, publish in one place.</span>
                  </div>
                  <div className="hero-summary-stats">
                    <div>
                      <strong>{totalPublished}</strong>
                      <span>Reports live</span>
                    </div>
                    <div>
                      <strong>{tags.length || 0}</strong>
                      <span>Topics tracked</span>
                    </div>
                    <div>
                      <strong>4-step</strong>
                      <span>QA pipeline</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="hero-glow" aria-hidden="true" />
        </section>

        {/* ─── Social proof bar ─── */}
        <section className="stats-bar">
          <div className="sb">
            <strong>{totalPublished}</strong>
            <span>Published Reports</span>
          </div>
          <div className="sb">
            <strong>{tags.length}</strong>
            <span>Research Topics</span>
          </div>
          <div className="sb">
            <strong>100%</strong>
            <span>Open Access</span>
          </div>
          <div className="sb">
            <strong>4</strong>
            <span>AI Agents</span>
          </div>
        </section>

        <section className="journeys">
          <div className="section-head">
            <div>
              <p className="section-eyebrow">Start Here</p>
              <h2>Find What You Need Faster</h2>
            </div>
          </div>
          <div className="journey-grid">
            {startCards.map((card) => (
              <Link href={card.href} key={card.title} className="journey-card">
                <div className="journey-media">
                  <Image src={card.image} alt={card.alt} width={520} height={340} />
                </div>
                <div className="journey-copy">
                  <h3>{card.title}</h3>
                  <p>{card.description}</p>
                  <span className="journey-cta">{card.cta} &rarr;</span>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* ─── Mission ─── */}
        <section className="mission">
          <p className="section-eyebrow">Our Mission</p>
          <h2>Why Baseflow Exists</h2>
          <p className="section-desc">Quality research on climate adaptation is too often paywalled, outdated, or unreachable. We&rsquo;re changing that.</p>
          <div className="mission-grid">
            <div className="m-card">
              <div className="m-icon-wrap"><span className="m-icon">🌍</span></div>
              <h3>Bridge the Knowledge Gap</h3>
              <p>Make evidence-based insights on global challenges freely available to policymakers, researchers, and the public.</p>
            </div>
            <div className="m-card">
              <div className="m-icon-wrap"><span className="m-icon">🤖</span></div>
              <h3>AI That Serves People</h3>
              <p>Our multi-agent pipeline draws from the World Bank, UN databases, and peer-reviewed sources to produce cited, policy-relevant briefs.</p>
            </div>
            <div className="m-card">
              <div className="m-icon-wrap"><span className="m-icon">📊</span></div>
              <h3>Evidence Over Opinion</h3>
              <p>Every report goes through research, planning, writing, and independent fact-checking. Unverified claims are flagged transparently.</p>
            </div>
          </div>
        </section>

        {/* ─── Latest Research ─── */}
        <section className="latest">
          <div className="section-head">
            <div>
              <p className="section-eyebrow">New Research</p>
              <h2>Latest Publications</h2>
            </div>
            {articles.length > 0 && <Link href="/library" className="see-all">View all &rarr;</Link>}
          </div>
          {loading ? (
            <div className="loading-placeholder">
              {[1,2,3].map(i => <div key={i} className="skeleton-card" />)}
            </div>
          ) : articles.length === 0 ? (
            <div className="empty-hero">
              <div className="empty-icon">
                <svg width="48" height="48" viewBox="0 0 48 48" fill="none"><rect x="8" y="6" width="32" height="36" rx="4" stroke="#94a3b8" strokeWidth="2"/><path d="M16 16h16M16 24h12M16 32h8" stroke="#94a3b8" strokeWidth="2" strokeLinecap="round"/></svg>
              </div>
              <h3>Research pipeline is warming up</h3>
              <p>The first reports are being researched and written by our AI agents. Subscribe below to be notified when they&rsquo;re ready.</p>
            </div>
          ) : (
            <div className="card-grid">
              {articles.map(a => (
                <Link href={`/article/${a.slug}`} key={a.slug} className="a-card">
                  <div className="a-meta">
                    <span className="a-tmpl">{a.template}</span>
                    {a.region && <span className="a-region">{a.region}</span>}
                  </div>
                  <h3>{a.title}</h3>
                  <p className="a-summary">{a.summary}</p>
                  <div className="a-foot">
                    <span>{formatDate(a.publishedAt)}</span>
                    <span className="a-dot">&middot;</span>
                    <span>{a.wordCount.toLocaleString()} words</span>
                  </div>
                  <div className="a-tags">
                    {a.tags.slice(0, 3).map(t => (
                      <span key={t} className="tag-sm">{tagLabels[t] || t}</span>
                    ))}
                  </div>
                </Link>
              ))}
            </div>
          )}
        </section>

        {/* ─── Pipeline / How It Works ─── */}
        <section className="pipeline" id="pipeline">
          <p className="section-eyebrow">Our Process</p>
          <h2>How Research Gets Made</h2>
          <p className="section-desc">Every report passes through a rigorous four-stage pipeline&mdash;from data discovery to verified publication.</p>
          <div className="pipeline-grid">
            {[
              { num: '01', icon: '🔬', title: 'Research & Discovery', desc: 'AI agents query DuckDuckGo, Wikipedia, World Bank, and UN databases, collecting current data, statistics, and source material.' },
              { num: '02', icon: '📐', title: 'Planning & Analysis', desc: 'A planning agent synthesizes findings, identifies a unique analytical angle, and creates a structured outline with key evidence.' },
              { num: '03', icon: '✍️', title: 'Writing & Citation', desc: 'A specialized writing agent drafts the full report with inline citations, clear structure, and policy-relevant conclusions.' },
              { num: '04', icon: '✅', title: 'Review & Fact-Check', desc: 'An independent fact-checking agent verifies every claim against sources. Unverified statistics are flagged before publication.' },
            ].map((step) => (
              <div key={step.num} className="pipe-card">
                <div className="pipe-card-head">
                  <span className="pipe-num">{step.num}</span>
                  <span className="pipe-icon">{step.icon}</span>
                </div>
                <h3>{step.title}</h3>
                <p>{step.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ─── Topics ─── */}
        {tags.length > 0 && (
          <section className="topics">
            <p className="section-eyebrow">Coverage Areas</p>
            <h2>Topics We Cover</h2>
            <div className="topic-cloud">
              {tags.map(({ tag, count }) => (
                <Link href={`/library?tag=${tag}`} key={tag}
                  className={`topic-pill ${count > 3 ? 'lg' : count > 1 ? 'md' : ''}`}>
                  {tagLabels[tag] || tag}<span className="tp-ct">{count}</span>
                </Link>
              ))}
            </div>
          </section>
        )}

        {/* ─── Newsletter ─── */}
        <section className="newsletter" id="newsletter">
          <div className="nl-card">
            <p className="section-eyebrow" style={{ color: 'var(--accent)' }}>Stay Updated</p>
            <h2>Get New Research in Your Inbox</h2>
            <p>Subscribe for notifications when new reports are published. No spam&mdash;only evidence-based insights.</p>
            <div className="nl-benefits" aria-label="Newsletter benefits">
              <span>Fresh publications only</span>
              <span>No marketing blasts</span>
              <span>Designed for researchers and policy teams</span>
            </div>
            <div className="nl-form">
              <input type="email" placeholder="you@example.com" value={email}
                onChange={e => setEmail(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleSubscribe()} />
              <button onClick={handleSubscribe} className="btn-primary">Subscribe</button>
            </div>
            {subscribeStatus && (
              <div className={`nl-status ${subscribeStatus.includes('Subscribed') ? 'ok' : 'err'}`} aria-live="polite">
                {subscribeStatus}
              </div>
            )}
          </div>
        </section>

        {/* ─── Open Data ─── */}
        <section className="open-data">
          <p className="section-eyebrow">Access & Transparency</p>
          <h2>Open by Design</h2>
          <div className="od-grid">
            <div className="od-item">
              <div className="od-icon">
                <svg width="28" height="28" viewBox="0 0 24 24" fill="none"><path d="M4 11a9 9 0 0 1 9-9m0 0a9 9 0 0 1 9 9M4 11l3 3m-3-3l3-3m13 3l-3 3m3-3l-3-3M13 2v4m0 12v4M13 2a9 9 0 0 0 0 18" stroke="var(--accent)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
              </div>
              <h3>RSS Feed</h3>
              <p>Follow new publications in your favourite feed reader.</p>
              <a href="/feed.xml" className="btn-outline">Subscribe via RSS</a>
            </div>
            <div className="od-item">
              <div className="od-icon">
                <svg width="28" height="28" viewBox="0 0 24 24" fill="none"><rect x="3" y="11" width="18" height="11" rx="2" stroke="var(--accent)" strokeWidth="1.5"/><path d="M7 11V7a5 5 0 1 1 10 0v4" stroke="var(--accent)" strokeWidth="1.5" strokeLinecap="round"/></svg>
              </div>
              <h3>Open Access</h3>
              <p>All research is free to read, share, cite, and redistribute. No paywall, ever.</p>
            </div>
            <div className="od-item">
              <div className="od-icon">
                <svg width="28" height="28" viewBox="0 0 24 24" fill="none"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9l-7-7z" stroke="var(--accent)" strokeWidth="1.5" strokeLinejoin="round"/><path d="M13 2v7h7" stroke="var(--accent)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
              </div>
              <h3>JSON API</h3>
              <p>Query and integrate research data programmatically via our public API.</p>
              <a href="/api/articles" className="btn-outline" target="_blank" rel="noreferrer">Explore API</a>
            </div>
          </div>
        </section>
    </main>
  );
}
