'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

type ArticlePreview = {
  slug: string;
  title: string;
  summary: string;
  tags: string[];
  template: string;
  region?: string;
  publishedAt: string;
  wordCount: number;
};

type TagCount = {
  tag: string;
  count: number;
};

export default function HomePage() {
  const [articles, setArticles] = useState<ArticlePreview[]>([]);
  const [tags, setTags] = useState<TagCount[]>([]);
  const [totalPublished, setTotalPublished] = useState(0);
  const [email, setEmail] = useState('');
  const [subscribeStatus, setSubscribeStatus] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      fetch('/api/articles?limit=6').then(r => r.ok ? r.json() : { articles: [], total: 0 }),
      fetch('/api/articles/tags').then(r => r.ok ? r.json() : { tags: [] }),
    ]).then(([articlesData, tagsData]) => {
      setArticles(articlesData.articles || []);
      setTags(tagsData.tags || []);
      setTotalPublished(articlesData.total || 0);
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  const handleSubscribe = async () => {
    if (!email.trim() || !email.includes('@')) {
      setSubscribeStatus('Please enter a valid email.');
      return;
    }
    try {
      const res = await fetch('/api/subscribe', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email }),
      });
      if (res.ok) {
        setSubscribeStatus('Subscribed! You\'ll receive updates on new research.');
        setEmail('');
      } else {
        const data = await res.json();
        setSubscribeStatus(data.error || 'Subscription failed.');
      }
    } catch {
      setSubscribeStatus('Connection error. Try again.');
    }
  };

  const formatDate = (iso: string) =>
    new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const tagLabels: Record<string, string> = {
    climate: 'Climate', water: 'Water Security', energy: 'Clean Energy',
    agriculture: 'Agriculture', health: 'Health', policy: 'Policy',
    finance: 'Finance', resilience: 'Resilience', biodiversity: 'Biodiversity',
    urbanization: 'Urbanization', education: 'Education', gender: 'Gender Equity',
    'sub-saharan-africa': 'Sub-Saharan Africa', 'south-asia': 'South Asia',
    'southeast-asia': 'Southeast Asia', 'latin-america': 'Latin America',
    'pacific-islands': 'Pacific Islands', 'middle-east': 'MENA',
  };

  return (
    <main className="pub">
      {/* Hero */}
      <section className="hero">
        <div className="hero-inner">
          <span className="hero-badge">Open Research Platform</span>
          <h1>AI-Powered Research for Global Development</h1>
          <p className="hero-sub">
            Free, evidence-based policy briefs on climate adaptation, water security,
            clean energy, and resilience&mdash;generated by AI, grounded in real data,
            available to everyone.
          </p>
          <div className="hero-actions">
            <Link href="/library" className="btn-primary">Browse Research Library &rarr;</Link>
            <Link href="/about" className="btn-ghost">How It Works</Link>
          </div>
        </div>
      </section>

      {/* Stats bar */}
      <section className="stats-bar">
        <div className="sb"><strong>{totalPublished}</strong><span>Reports</span></div>
        <div className="sb"><strong>{tags.length}</strong><span>Topics</span></div>
        <div className="sb"><strong>100%</strong><span>Open Access</span></div>
        <div className="sb"><strong>Free</strong><span>Always</span></div>
      </section>

      {/* Mission */}
      <section className="mission">
        <h2>Why This Exists</h2>
        <div className="mission-grid">
          <div className="m-card">
            <div className="m-icon">🌍</div>
            <h3>Bridge the Knowledge Gap</h3>
            <p>Quality research on climate adaptation is often paywalled or inaccessible. We make evidence-based insights free for everyone.</p>
          </div>
          <div className="m-card">
            <div className="m-icon">🤖</div>
            <h3>AI That Serves People</h3>
            <p>Our AI pipeline researches real data from the World Bank, UN agencies, and peer-reviewed sources to produce cited, policy-relevant briefs.</p>
          </div>
          <div className="m-card">
            <div className="m-icon">📊</div>
            <h3>Evidence Over Opinion</h3>
            <p>Every report goes through research, planning, writing, and fact-checking. Unverified statistics are flagged transparently.</p>
          </div>
        </div>
      </section>

      {/* Latest Research */}
      <section className="latest">
        <div className="section-head">
          <h2>Latest Research</h2>
          {articles.length > 0 && <Link href="/library" className="see-all">View all &rarr;</Link>}
        </div>
        {loading ? (
          <p className="muted center">Loading...</p>
        ) : articles.length === 0 ? (
          <div className="empty-hero">
            <div style={{ fontSize: 48 }}>📝</div>
            <h3>Research is being generated</h3>
            <p>The first reports are being researched and written. Subscribe below to get notified, or <Link href="/admin">generate one now</Link>.</p>
          </div>
        ) : (
          <div className="card-grid">
            {articles.map(a => (
              <Link href={`/article/${a.slug}`} key={a.slug} className="a-card">
                <div className="a-meta">
                  <span className="a-tmpl">{a.template}</span>
                  {a.region && <span className="a-region">{a.region}</span>}
                </div>
                <h3>{a.title}</h3>
                <p className="a-summary">{a.summary}</p>
                <div className="a-foot">
                  <span>{formatDate(a.publishedAt)}</span>
                  <span>{a.wordCount} words</span>
                </div>
                <div className="a-tags">
                  {a.tags.slice(0, 4).map(t => (
                    <span key={t} className="tag-sm">{tagLabels[t] || t}</span>
                  ))}
                </div>
              </Link>
            ))}
          </div>
        )}
      </section>

      {/* Topics */}
      {tags.length > 0 && (
        <section className="topics">
          <h2>Topics We Cover</h2>
          <div className="topic-cloud">
            {tags.map(({ tag, count }) => (
              <Link href={`/library?tag=${tag}`} key={tag}
                className={`topic-pill ${count > 3 ? 'lg' : count > 1 ? 'md' : ''}`}>
                {tagLabels[tag] || tag}<span className="tp-ct">{count}</span>
              </Link>
            ))}
          </div>
        </section>
      )}

      {/* Newsletter */}
      <section className="newsletter">
        <div className="nl-card">
          <h2>Stay Informed</h2>
          <p>Get notified when new research is published. No spam&mdash;only evidence-based insights.</p>
          <div className="nl-form">
            <input type="email" placeholder="your@email.com" value={email}
              onChange={e => setEmail(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleSubscribe()} />
            <button onClick={handleSubscribe} className="btn-primary">Subscribe</button>
          </div>
          {subscribeStatus && (
            <div className={`nl-status ${subscribeStatus.includes('Subscribed') ? 'ok' : 'err'}`}>
              {subscribeStatus}
            </div>
          )}
        </div>
      </section>

      {/* Pipeline */}
      <section className="pipeline">
        <h2>How Our Research Pipeline Works</h2>
        <div className="pipe-row">
          {[
            { n: 1, t: 'Web Research', d: 'AI agents search DuckDuckGo, Wikipedia, World Bank, and UN databases for real data.' },
            { n: 2, t: 'Planning', d: 'A planner agent creates a unique angle and identifies key evidence to cite.' },
            { n: 3, t: 'Writing', d: 'A writer agent drafts the full report with inline citations.' },
            { n: 4, t: 'Fact-Check', d: 'A fact-checking pass verifies claims and flags anything unverified.' },
          ].map((s, i) => (
            <div key={s.n} className="pipe-step-wrap">
              {i > 0 && <div className="pipe-arrow">→</div>}
              <div className="pipe-step">
                <div className="pipe-n">{s.n}</div>
                <h3>{s.t}</h3>
                <p>{s.d}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Open data */}
      <section className="open-data">
        <div className="od-grid">
          <div className="od-item">
            <h3>📡 RSS Feed</h3>
            <p>Subscribe in your feed reader.</p>
            <a href="/feed.xml" className="btn-outline">RSS Feed</a>
          </div>
          <div className="od-item">
            <h3>🔓 Open Access</h3>
            <p>All research is free to read, share, and cite.</p>
          </div>
          <div className="od-item">
            <h3>📂 API Access</h3>
            <p>Pull research data via JSON API.</p>
            <a href="/api/articles" className="btn-outline" target="_blank" rel="noreferrer">API Docs</a>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="site-footer">
        <div className="ft-top">
          <div>
            <strong>Open Policy Research Hub</strong>
            <p className="muted">AI-powered research for a more resilient world.</p>
          </div>
          <nav className="ft-nav">
            <Link href="/library">Library</Link>
            <Link href="/about">About</Link>
            <a href="/feed.xml">RSS</a>
            <Link href="/admin">Admin</Link>
          </nav>
        </div>
        <p className="ft-note">Research generated by AI with real-world data. Always verify critical decisions with primary sources.</p>
      </footer>
    </main>
  );
}
